### ISSUE TITLE
Annotations are "unknown category" when detection model give category that is not in COCO JSON 

### ISSUE THREAD

**Issue by PaulHax** [Kitware/nrtk-explorer#73]
When loading the OIRDS dataset:
```
nrtk-explorer --dataset ./nrtk_explorer_datasets/OIRDS_v1_0/oirds.json
```
The default "object detection model" is `facebook/detr-resnet-50`.  The categories that model emits are not in the OIRDS category list. This causes the annotation bounding box to be labeled `0: Unknown` category.  
![image](https://github.com/Kitware/nrtk-explorer/assets/16823231/837d1043-e084-4742-a801-e3020cbb17fb)
Would be nicer if we showed the category the model emitted, even if its not in the COCO JSON.

**Comment by vicentebolea** [comment]
The reason of this is that facebook/detr-resnet-50 uses only the categories from the dataset that we use the COCO 2017 object detection dataset. The reason of this `0: unknown' is that the cocoscorer expects the categories from the prediction to be in the coco json dataset. a workaround is to set the categories not in the dataset as 0.

**Comment by PaulHax** [comment]
Addressed the display aspect of this here: https://github.com/vicentebolea/nrtk-explore/pull/1/commits/573b4747f50c1f2c66ec8dcf5fe35f7d0ef98abc
