### ISSUE TITLE
Category Filter only filters object detection model results, not ground truth 

### ISSUE THREAD

**Issue by PaulHax** [Kitware/nrtk-explorer#74]
Thats strange because if you
1. "Apply" category filter with `cow` as a item, no images are selected
2. Select the zebra and wildabeast image.  Detection model annotates the wildabeast as cow.
3. "Apply" category filter with `cow` as a item -> Surprise! Zebra/Wildabeast image is selected.
4. Deselect Zebra/Wildabeast
5. "Apply" category filter with `cow` as a item -> Surprise: no images are selected (but Zebra/Wildabeast was selected before!)

Strange that we select images based on if they are currently selected.  If thats what we want, then category tags need to be updated on each image set selection. 

Relevent code:
https://github.com/Kitware/nrtk-explorer/blob/main/src/nrtk_explorer/app/core.py#L146-L149

**Comment by vicentebolea** [comment]
Thanks for pointing this out, we probably want to filter ground truth.
