### ISSUE TITLE
CUDA memory leak 

### ISSUE THREAD

**Issue by PaulHax** [Kitware/nrtk-explorer#85]
## Steps
1. Load up the OIRDS dataset from nrtk_explorer_datasets repo.
2. Compute embeddings for 300+
3. Select a chunk out of the cloud with box select
4. Error: `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 983.00 MiB. GPU`
5. Select a smaller set of images. All OK.
6. Select a slightly bigger set, another error indicating leak:   `torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 314.00 MiB. GPU`

**Comment by vicentebolea** [comment]
This is probably not a leak but that OOM of the dataset, we have to adjust the batching parameter for larger datasets depending on one's hw.

**Comment by PaulHax** [comment]
The Tried to allocate number keeps going down, even though I selected less images.
